# Generated by Django 5.1.4 on 2025-01-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.ImageField(upload_to='images/')),
                ('width', models.PositiveIntegerField(editable=False)),
                ('height', models.PositiveIntegerField(editable=False)),
                ('channels', models.PositiveIntegerField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to='pdfs/')),
                ('number_of_pages', models.PositiveIntegerField(editable=False)),
                ('page_width', models.FloatField(editable=False)),
                ('page_height', models.FloatField(editable=False)),
            ],
        ),
    ]
