# Generated by Django 5.1.4 on 2025-01-08 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_uploadedimage_channels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedpdf',
            name='number_of_pages',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedpdf',
            name='page_height',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedpdf',
            name='page_width',
            field=models.FloatField(editable=False, null=True),
        ),
    ]
